allowBuilds:
  '@prisma/engines': true
  base64: true
  bcrypt: true
  esbuild: true
  msw: true
  prisma: true
  sharp: true
  tesseract.js: true
  unrs-resolver: true
auditConfig:
  ignoreGhsas:
    - GHSA-r28c-9q8g-f849
    - GHSA-qx2v-qp2m-jg93
    - GHSA-fxqj-rqcc-2cmp
